name: Lint and Fix

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd frontend && npm ci --legacy-peer-deps

    - name: Lint and Fix
      run: cd frontend && npm run lint || npm run lint:fix

    - name: Prettify
      run: cd frontend && npm run prettify

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Fix lint errors" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        branch: ${{ github.ref }}